import Head from 'next/head'
import Header from '../component/home/Header'
import Footer from '../component/home/Footer'
import Loader from '../component/home/Loader'

import InnerBanner from '../component/about/InnerBanner'
import Ourbeginnings from '../component/about/Ourbeginnings'
import Ourvalue from '../component/about/Ourvalue'
import MeetOuteam from '../component/about/MeetOuteam'
import Partners from '../component/about/Partners'
import Ctasection from '../component/about/Ctasection'

export default function Home() {
  return (
    <div className="main-wrapper about_page">
        <Head>
            <title>About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
        </Head>

        <Loader/>
        <Header/>
        <div className='main-contain about_page'>
            <InnerBanner />
            <Ourbeginnings />
            <Ourvalue />
            <MeetOuteam />
            <Partners />
            <Ctasection />
        </div>
        <Footer />
    </div>
  )
}
