import Head from 'next/head'
import Header from '../component/home/Header'
import Homebanner from '../component/home/Homebanner'
import Whatwestrive from '../component/home/Whatwestrive'
import OurExpertise from '../component/home/OurExpertise'
import Project from '../component/home/Project'

export default function Home() {
  return (
    <div className="main-wrapper">
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header/>
        <div className='main-contain'>
            <Homebanner />
            <Whatwestrive />
            <OurExpertise />
            <Project />
        </div>
    </div>
  )
}
