import Head from 'next/head'
import Header from '../component/home/Header'
import Footer from '../component/home/Footer'
import Loader from '../component/home/Loader'

import InnerBanner from '../component/Process/Innerbanner'
import FourFoldApproach from '../component/Process/FourFoldApproach'
import HappyClient from '../component/Process/HappyClient'
import Ctaouter from '../component/Process/Ctaouter'


export default function Home() {
  return (
    <div className="main-wrapper process_page">
        <Head>
            <title>Process</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
        </Head>

        <Loader/>
        <Header/>
        <div className='main-contain'>
            <InnerBanner />
            <FourFoldApproach />
            <HappyClient />
            <Ctaouter />
        </div>
        <Footer />
    </div>
  )
}
