import Head from 'next/head'
import Header from '../component/home/Header'
import Footer from '../component/home/Footer'
import Loader from '../component/home/Loader'

import Innerbanner from '../component/project/Innerbanner'
import Casesection from '../component/project/Casesection'
import Ctaouter from '../component/project/Ctaouter'



export default function Home() {
  return (
    <div className="main-wrapper project_page">
        <Head>
            <title>Process</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
        </Head>

        <Loader/>
        <Header/>
        <div className='main-contain project_page'>
            <Innerbanner />
            <Casesection />
            <Ctaouter />
        </div>
        <Footer />
    </div>
  )
}
