import Head from 'next/head'
import Header from '../component/home/Header'
import Footer from '../component/home/Footer'
import Loader from '../component/home/Loader'

import InnerBanner from '../component/sanfrancisco/Innerbanner'
import Case_content from '../component/sanfrancisco/Case_content'
import Platform from '../component/sanfrancisco/Platform'
import The_challege from '../component/sanfrancisco/The_challege'
import RebuildingEntire from '../component/sanfrancisco/RebuildingEntire'



export default function Home() {
  return (
    <div className="main-wrapper san_francisco_page common_inner_page">
        <Head>
            <title>Process</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
        </Head>

        <Loader/>
        <Header/>
        <div className='main-contain project_page'>
            <InnerBanner />
            <Case_content />
            <Platform />
            <The_challege />
            <RebuildingEntire />
        </div>
        <Footer />
    </div>
  )
}
